### ISSUE TITLE
Wrong variable name in documentation for IonQ-Plugin - API-Key

### ISSUE THREAD

**Issue by p3nrose** [PennyLaneAI/PennyLane-IonQ#95]
In the documentation [https://docs.pennylane.ai/projects/ionq/en/latest/index.html](https://docs.pennylane.ai/projects/ionq/en/latest/index.html) the variable name for the api key is `IONQ_API_KEY` but this wont work.
The variable name in the `config.toml` file should be `api_key = "YOUR-IONQ-KEY"`. I tested it and it works 😉 

```toml
[main]
# global settings

[ionq.global]
# Global option for  the IonQ plugin
api_key = "ABCD1234_YOUR_KEY"

```
